version: "3.8"

services:
  app:
    container_name: "app"
    build: "."
    hostname: v2ray-tel-bot
    volumes:
      - ./config/config.yml:/app/config/config.yml
    networks:
      - v2tel
    command: ["python", "./bot.py"]

networks:
  v2tel:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.1.0/24
          gateway: 10.1.1.1