telegram_token: ""
channel_id: "" #If you want to force the user to join the channel, please provide your channel's numeric ID (-1243423432). Otherwise, put None

panels:
  - url: http://web.example.com:54321
    username: admin
    password: admin
  
  # - url: https://web.example.com:54321
  #   username: admin
  #   password: admin